### ISSUE TITLE
Feature request: Override config override_function when calling fastaction.select

### ISSUE THREAD

**Issue by gustavkrist** [Chaitanyabsprip/fastaction.nvim#14]
Ideally I want to use action markers from keys when invoking `fastaction.select` from `vim.ui.select` and the priority/title based action markers when opening the lsp action window. I can't figure out a way to do this through the config/parameters for `fastaction.select`. I have gotten it to always use the key action markers by copying `get_action_config_from_keys` https://github.com/Chaitanyabsprip/fastaction.nvim/blob/main/lua/fastaction/keys.lua#L29 and using it as my `override_function` in the config, but then I lose the priority/title keys in the lsp action window.

A solution that would be easy to implement would be allowing to specify an `override_function` in the parameters to `fastaction.select` and using that if it is present and the function from the config otherwise. It might also be nice with some way of specifying an ordering of the funcs in `fastaction.keys.get_action_config` https://github.com/Chaitanyabsprip/fastaction.nvim/blob/main/lua/fastaction/keys.lua#L56 in the `fastaction.select` parameters if there is any sensible way of doing so. This would make it possible to use different action markers in different situations without having to copy over the currently private functions and use them as `override_function`.

**Comment by Chaitanyabsprip** [comment]
I'm thinking of completely discarding the code_action and range_code_action functions, OR instead of redoing the whole lsp logic, use the select method itself. This way I can move the override_function to the select callback.

A quicker and concise solution would be to make override_function apply only for LSP helper functions (code_actions). And also add an override_function callback to select function.

Seems like either way I'll have to add an override_function callback to select function.

Thanks for the elaborate issue @gustavkrist.

**Comment by Chaitanyabsprip** [comment]
I added a `kind` field to the params passed to the `override_function`. You can now handle the different context based on the value of `kind` value.
